# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: quantum_gateway
    host: 192.168.1.1
    password: !secret fios_gateway_password

http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.1.254

browser:
